module.exports = {
  familySchemaValidator: require("./family"),
  pinnedMessageValidator: require("./pinnedMessage"),
  reactMessageValidator: require("./reactMessage"),
  commisionRateValidator: require("./commisionRate"),
  familyRuleValidator: require("./familyRules"),
  inviteAgent: require('./inviteAgent'),
  otp: require('./otp'),
  momentPost: require('./momentPost').momentSchema,
  postLikeSchema: require('./momentPost').postLikeSchema,
  postCommentSchema: require('./momentPost').postCommentSchema,
  postActiveSchema: require('./momentPost').postActiveSchema,
  productCategory: require('./productCategory'),
  liveStreamTag: require('./liveStreamTag'),
  userLiveStreamTag: require('./userLiveStreamTag'),
  subcriptionPackageSchema: require('./subscriptionPackage'),
  packagePrivilege: require('./packagePrivilege'),
  guardianValidation: require('./guardianValidation'),
  pkValidation: require('./pk'),
  entranceEffect: require('./entranceEffect'),
  productSchema: require('./product').productSchema,
  productParamSchema: require('./product').productCategoryParamSchema,
  productIdParamSchema: require('./product').productIdParamSchema,
  activeProduct : require('./product').productActive,
  buyProduct: require('./buyProduct'),
  sendProductSchema: require('./sendProduct'),
  specialrid: require('./specialRid'),
  paramsIdValidation:  require('./paramIdValidation'),
  dailyReward:  require('./dailyReward'),
  Banner: require('./banner'),
  senderlevelInfo: require('./senderLevelInfo'),
  hostlevelInfo: require('./hostLevelInfo'),
  updateFamilyStatus: require('./updateFamilyStatus')
};
